"""migrate

Revision ID: d5bcee383afa
Revises: 2fc70cafe580
Create Date: 2024-03-21 12:48:43.914426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bcee383afa'
down_revision = '2fc70cafe580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('biography', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('biography')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
